### PR TITLE
fix(processor): fields with override do not work

### PR DESCRIPTION
**Pull request by nothendev**
This PR contains a fix for the processor to not add the override modifier to fields of PartialX classes

(sorry in advance for a lot of mistakes, it's because currently I'm unable to edit code except in browser from phone, where code completion is nonexistent and you see errors only in workflow runs)

### CODE REVIEW

**Comment by rushiiMachine** [comment]
The override modifier is needed though when you you're extending a parent that gets partialized too...

**Comment by X1nto** [comment]
Could you please provide an example case where the current implementation fails and this PR fixes it?

**Comment by nothendev** [comment]
```kt
interface Snowflake {
    val id: String
}

@Partialize
data class User(
    override val id: String,
    val name: String,
    val email: String
) : Snowflake
```
On the PartialUser class it incorrectly puts override on val id, and does not extend Snowflake (and cannot, because it requires id to be String, not Partial<String>)

**Comment by nothendev** [comment]
Okay, I think the processor could remove override for interfaces that aren't @Partialize'd

**Comment by nothendev** [comment]
It is done! You could approve workflow, it'll build great!

**Comment by rushiiMachine** [comment]
can you reformat that line
too long

**Comment by nothendev** [comment]
Yay! Now the PR is ready!

**Pull request merged**
